import json
from pathlib import Path

FLAGS_FILE = Path("flags.json")

# First-pass visual tags. This is intentionally visual, not heraldic/legal.
# Use broad labels so the graph has useful associations.
SPECIFIC = {
    "afghanistan": {"colors": ["black", "white"], "layout": ["solid-field", "centered-text"], "symbols": ["script"]},
    "albania": {"colors": ["red", "black"], "layout": ["solid-field", "centered-emblem"], "symbols": ["eagle"]},
    "algeria": {"colors": ["green", "white", "red"], "layout": ["vertical-bicolor", "centered-emblem"], "symbols": ["crescent", "star"]},
    "andorra": {"colors": ["blue", "yellow", "red"], "layout": ["vertical-tricolor", "centered-emblem"], "symbols": ["coat-of-arms"]},
    "angola": {"colors": ["red", "black", "yellow"], "layout": ["horizontal-bicolor", "centered-emblem"], "symbols": ["star", "weapon", "gear"]},
    "antigua-and-barbuda": {"colors": ["red", "black", "blue", "white", "yellow"], "layout": ["triangle", "horizontal-bands"], "symbols": ["sun"]},
    "argentina": {"colors": ["blue", "white", "yellow"], "layout": ["horizontal-triband", "centered-emblem"], "symbols": ["sun"]},
    "armenia": {"colors": ["red", "blue", "orange"], "layout": ["horizontal-tricolor"], "symbols": []},
    "australia": {"colors": ["blue", "white", "red"], "layout": ["canton"], "symbols": ["stars", "union-jack"]},
    "austria": {"colors": ["red", "white"], "layout": ["horizontal-triband"], "symbols": []},
    "azerbaijan": {"colors": ["blue", "red", "green", "white"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["crescent", "star"]},
    "bahamas": {"colors": ["blue", "yellow", "black"], "layout": ["horizontal-triband", "hoist-triangle"], "symbols": []},
    "bahrain": {"colors": ["red", "white"], "layout": ["vertical-bicolor", "serrated"], "symbols": []},
    "bangladesh": {"colors": ["green", "red"], "layout": ["solid-field", "centered-emblem"], "symbols": ["disc", "sun"]},
    "barbados": {"colors": ["blue", "yellow", "black"], "layout": ["vertical-tricolor", "centered-emblem"], "symbols": ["trident"]},
    "belarus": {"colors": ["red", "green", "white"], "layout": ["horizontal-bicolor", "hoist-pattern"], "symbols": ["ornament"]},
    "belgium": {"colors": ["black", "yellow", "red"], "layout": ["vertical-tricolor"], "symbols": []},
    "belize": {"colors": ["blue", "red", "white", "green", "brown"], "layout": ["solid-field", "border-stripes", "centered-emblem"], "symbols": ["coat-of-arms", "people", "wreath"]},
    "benin": {"colors": ["green", "yellow", "red"], "layout": ["vertical-hoist", "horizontal-bicolor"], "symbols": []},
    "bhutan": {"colors": ["yellow", "orange", "white"], "layout": ["diagonal-bicolor", "centered-emblem"], "symbols": ["dragon"]},
    "bolivia": {"colors": ["red", "yellow", "green"], "layout": ["horizontal-tricolor"], "symbols": []},
    "bosnia-and-herzegovina": {"colors": ["blue", "yellow", "white"], "layout": ["diagonal", "right-triangle"], "symbols": ["stars"]},
    "botswana": {"colors": ["blue", "black", "white"], "layout": ["horizontal-stripes"], "symbols": []},
    "brazil": {"colors": ["green", "yellow", "blue", "white"], "layout": ["solid-field", "centered-emblem"], "symbols": ["disc", "stars", "text"]},
    "brunei": {"colors": ["yellow", "white", "black", "red"], "layout": ["diagonal-stripes", "centered-emblem"], "symbols": ["crest"]},
    "bulgaria": {"colors": ["white", "green", "red"], "layout": ["horizontal-tricolor"], "symbols": []},
    "burkina-faso": {"colors": ["red", "green", "yellow"], "layout": ["horizontal-bicolor", "centered-emblem"], "symbols": ["star"]},
    "burundi": {"colors": ["red", "green", "white"], "layout": ["diagonal-cross", "centered-emblem"], "symbols": ["stars"]},
    "cambodia": {"colors": ["blue", "red", "white"], "layout": ["horizontal-triband", "centered-emblem"], "symbols": ["building"]},
    "cameroon": {"colors": ["green", "red", "yellow"], "layout": ["vertical-tricolor", "centered-emblem"], "symbols": ["star"]},
    "canada": {"colors": ["red", "white"], "layout": ["vertical-triband", "centered-emblem"], "symbols": ["leaf"]},
    "cape-verde": {"colors": ["blue", "white", "red", "yellow"], "layout": ["horizontal-stripes"], "symbols": ["stars"]},
    "central-african-republic": {"colors": ["blue", "white", "green", "yellow", "red"], "layout": ["horizontal-stripes", "vertical-stripe"], "symbols": ["star"]},
    "chad": {"colors": ["blue", "yellow", "red"], "layout": ["vertical-tricolor"], "symbols": []},
    "chile": {"colors": ["red", "white", "blue"], "layout": ["horizontal-bicolor", "canton"], "symbols": ["star"]},
    "china": {"colors": ["red", "yellow"], "layout": ["solid-field", "canton"], "symbols": ["stars"]},
    "colombia": {"colors": ["yellow", "blue", "red"], "layout": ["horizontal-tricolor"], "symbols": []},
    "comoros": {"colors": ["yellow", "white", "red", "blue", "green"], "layout": ["horizontal-stripes", "hoist-triangle"], "symbols": ["crescent", "stars"]},
    "cook-islands": {"colors": ["blue", "white", "red"], "layout": ["canton"], "symbols": ["stars", "union-jack"]},
    "costa-rica": {"colors": ["blue", "white", "red"], "layout": ["horizontal-stripes"], "symbols": []},
    "co-te-divoire": {"colors": ["orange", "white", "green"], "layout": ["vertical-tricolor"], "symbols": []},
    "croatia": {"colors": ["red", "white", "blue"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["coat-of-arms", "shield"]},
    "cuba": {"colors": ["blue", "white", "red"], "layout": ["stripes", "hoist-triangle"], "symbols": ["star"]},
    "cyprus": {"colors": ["white", "orange", "green"], "layout": ["solid-field", "centered-emblem"], "symbols": ["map", "branches"]},
    "czech-republic": {"colors": ["white", "red", "blue"], "layout": ["horizontal-bicolor", "hoist-triangle"], "symbols": []},
    "democratic-republic-of-the-congo": {"colors": ["blue", "yellow", "red"], "layout": ["diagonal-stripe"], "symbols": ["star"]},
    "denmark": {"colors": ["red", "white"], "layout": ["nordic-cross"], "symbols": ["cross"]},
    "djibouti": {"colors": ["blue", "green", "white", "red"], "layout": ["horizontal-bicolor", "hoist-triangle"], "symbols": ["star"]},
    "dominica": {"colors": ["green", "yellow", "black", "white", "red", "purple"], "layout": ["cross", "centered-emblem"], "symbols": ["bird", "stars", "disc"]},
    "dominican-republic": {"colors": ["blue", "red", "white"], "layout": ["quartered", "centered-cross", "centered-emblem"], "symbols": ["coat-of-arms", "cross"]},
    "east-timor": {"colors": ["red", "yellow", "black", "white"], "layout": ["hoist-triangle"], "symbols": ["star"]},
    "ecuador": {"colors": ["yellow", "blue", "red"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["coat-of-arms"]},
    "egypt": {"colors": ["red", "white", "black", "yellow"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["eagle"]},
    "el-salvador": {"colors": ["blue", "white"], "layout": ["horizontal-triband", "centered-emblem"], "symbols": ["coat-of-arms"]},
    "england": {"colors": ["white", "red"], "layout": ["centered-cross"], "symbols": ["cross"]},
    "equatorial-guinea": {"colors": ["green", "white", "red", "blue"], "layout": ["horizontal-tricolor", "hoist-triangle", "centered-emblem"], "symbols": ["coat-of-arms"]},
    "eritrea": {"colors": ["green", "red", "blue", "yellow"], "layout": ["diagonal-triangles", "centered-emblem"], "symbols": ["wreath", "branch"]},
    "estonia": {"colors": ["blue", "black", "white"], "layout": ["horizontal-tricolor"], "symbols": []},
    "eswatini": {"colors": ["blue", "yellow", "red", "black", "white"], "layout": ["horizontal-stripes", "centered-emblem"], "symbols": ["shield", "spears"]},
    "ethiopia": {"colors": ["green", "yellow", "red", "blue"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["star", "disc"]},
    "micronesia": {"colors": ["blue", "white"], "layout": ["solid-field", "centered-emblem"], "symbols": ["stars"]},
    "fiji": {"colors": ["blue", "white", "red"], "layout": ["canton"], "symbols": ["union-jack", "shield"]},
    "finland": {"colors": ["white", "blue"], "layout": ["nordic-cross"], "symbols": ["cross"]},
    "france": {"colors": ["blue", "white", "red"], "layout": ["vertical-tricolor"], "symbols": []},
    "gabon": {"colors": ["green", "yellow", "blue"], "layout": ["horizontal-tricolor"], "symbols": []},
    "gambia": {"colors": ["red", "blue", "green", "white"], "layout": ["horizontal-stripes"], "symbols": []},
    "georgia": {"colors": ["white", "red"], "layout": ["cross", "quartered"], "symbols": ["cross"]},
    "germany": {"colors": ["black", "red", "yellow"], "layout": ["horizontal-tricolor"], "symbols": []},
    "ghana": {"colors": ["red", "yellow", "green", "black"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["star"]},
    "greece": {"colors": ["blue", "white"], "layout": ["stripes", "canton"], "symbols": ["cross"]},
    "grenada": {"colors": ["red", "yellow", "green"], "layout": ["border", "diagonal-triangles", "centered-emblem"], "symbols": ["stars", "nutmeg", "disc"]},
    "guatemala": {"colors": ["blue", "white"], "layout": ["vertical-triband", "centered-emblem"], "symbols": ["coat-of-arms", "bird"]},
    "guinea": {"colors": ["red", "yellow", "green"], "layout": ["vertical-tricolor"], "symbols": []},
    "guinea-bissau": {"colors": ["red", "yellow", "green", "black"], "layout": ["vertical-hoist", "horizontal-bicolor"], "symbols": ["star"]},
    "guyana": {"colors": ["green", "white", "yellow", "black", "red"], "layout": ["nested-triangles", "hoist-triangle"], "symbols": []},
    "haiti": {"colors": ["blue", "red", "white"], "layout": ["horizontal-bicolor", "centered-emblem"], "symbols": ["coat-of-arms"]},
    "honduras": {"colors": ["blue", "white"], "layout": ["horizontal-triband", "centered-emblem"], "symbols": ["stars"]},
    "hong-kong": {"colors": ["red", "white"], "layout": ["solid-field", "centered-emblem"], "symbols": ["flower", "stars"]},
    "hungary": {"colors": ["red", "white", "green"], "layout": ["horizontal-tricolor"], "symbols": []},
    "iceland": {"colors": ["blue", "white", "red"], "layout": ["nordic-cross"], "symbols": ["cross"]},
    "india": {"colors": ["orange", "white", "green", "blue"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["wheel"]},
    "indonesia": {"colors": ["red", "white"], "layout": ["horizontal-bicolor"], "symbols": []},
    "iran": {"colors": ["green", "white", "red"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["emblem", "script"]},
    "iraq": {"colors": ["red", "white", "black", "green"], "layout": ["horizontal-tricolor", "centered-text"], "symbols": ["script"]},
    "ireland": {"colors": ["green", "white", "orange"], "layout": ["vertical-tricolor"], "symbols": []},
    "israel": {"colors": ["blue", "white"], "layout": ["horizontal-stripes", "centered-emblem"], "symbols": ["star-of-david"]},
    "italy": {"colors": ["green", "white", "red"], "layout": ["vertical-tricolor"], "symbols": []},
    "jamaica": {"colors": ["green", "yellow", "black"], "layout": ["diagonal-cross"], "symbols": ["saltire"]},
    "japan": {"colors": ["white", "red"], "layout": ["solid-field", "centered-emblem"], "symbols": ["disc", "sun"]},
    "jordan": {"colors": ["black", "white", "green", "red"], "layout": ["horizontal-tricolor", "hoist-triangle"], "symbols": ["star"]},
    "kazakhstan": {"colors": ["blue", "yellow"], "layout": ["solid-field", "centered-emblem", "hoist-pattern"], "symbols": ["sun", "eagle", "ornament"]},
    "kenya": {"colors": ["black", "red", "green", "white"], "layout": ["horizontal-stripes", "centered-emblem"], "symbols": ["shield", "spears"]},
    "kiribati": {"colors": ["red", "white", "blue", "yellow"], "layout": ["horizontal-waves", "centered-emblem"], "symbols": ["sun", "bird"]},
    "kosovo": {"colors": ["blue", "yellow", "white"], "layout": ["solid-field", "centered-emblem"], "symbols": ["map", "stars"]},
    "kuwait": {"colors": ["green", "white", "red", "black"], "layout": ["horizontal-tricolor", "hoist-trapezoid"], "symbols": []},
    "kyrgyzstan": {"colors": ["red", "yellow"], "layout": ["solid-field", "centered-emblem"], "symbols": ["sun"]},
    "laos": {"colors": ["red", "blue", "white"], "layout": ["horizontal-triband", "centered-emblem"], "symbols": ["disc"]},
    "latvia": {"colors": ["red", "white"], "layout": ["horizontal-triband"], "symbols": []},
    "lebanon": {"colors": ["red", "white", "green"], "layout": ["horizontal-triband", "centered-emblem"], "symbols": ["tree"]},
    "lesotho": {"colors": ["blue", "white", "green", "black"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["hat"]},
    "liberia": {"colors": ["red", "white", "blue"], "layout": ["stripes", "canton"], "symbols": ["star"]},
    "libya": {"colors": ["red", "black", "green", "white"], "layout": ["horizontal-triband", "centered-emblem"], "symbols": ["crescent", "star"]},
    "liechtenstein": {"colors": ["blue", "red", "yellow"], "layout": ["horizontal-bicolor"], "symbols": ["crown"]},
    "lithuania": {"colors": ["yellow", "green", "red"], "layout": ["horizontal-tricolor"], "symbols": []},
    "luxembourg": {"colors": ["red", "white", "blue"], "layout": ["horizontal-tricolor"], "symbols": []},
    "madagascar": {"colors": ["white", "red", "green"], "layout": ["vertical-hoist", "horizontal-bicolor"], "symbols": []},
    "malawi": {"colors": ["black", "red", "green"], "layout": ["horizontal-tricolor"], "symbols": ["sun"]},
    "malaysia": {"colors": ["red", "white", "blue", "yellow"], "layout": ["stripes", "canton"], "symbols": ["crescent", "star"]},
    "maldives": {"colors": ["red", "green", "white"], "layout": ["border", "centered-emblem"], "symbols": ["crescent"]},
    "mali": {"colors": ["green", "yellow", "red"], "layout": ["vertical-tricolor"], "symbols": []},
    "malta": {"colors": ["white", "red"], "layout": ["vertical-bicolor", "canton"], "symbols": ["cross"]},
    "marshall-islands": {"colors": ["blue", "white", "orange"], "layout": ["diagonal-stripes"], "symbols": ["star"]},
    "mauritania": {"colors": ["green", "yellow", "red"], "layout": ["horizontal-stripes", "centered-emblem"], "symbols": ["crescent", "star"]},
    "mauritius": {"colors": ["red", "blue", "yellow", "green"], "layout": ["horizontal-stripes"], "symbols": []},
    "mexico": {"colors": ["green", "white", "red"], "layout": ["vertical-tricolor", "centered-emblem"], "symbols": ["coat-of-arms", "eagle"]},
    "moldova": {"colors": ["blue", "yellow", "red"], "layout": ["vertical-tricolor", "centered-emblem"], "symbols": ["coat-of-arms", "eagle"]},
    "monaco": {"colors": ["red", "white"], "layout": ["horizontal-bicolor"], "symbols": []},
    "mongolia": {"colors": ["red", "blue", "yellow"], "layout": ["vertical-triband"], "symbols": ["soyombo"]},
    "montenegro": {"colors": ["red", "yellow"], "layout": ["border", "centered-emblem"], "symbols": ["coat-of-arms", "eagle"]},
    "morocco": {"colors": ["red", "green"], "layout": ["solid-field", "centered-emblem"], "symbols": ["star"]},
    "mozambique": {"colors": ["green", "black", "yellow", "white", "red"], "layout": ["horizontal-stripes", "hoist-triangle"], "symbols": ["star", "book", "weapon"]},
    "myanmar": {"colors": ["yellow", "green", "red", "white"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["star"]},
    "namibia": {"colors": ["blue", "red", "green", "white", "yellow"], "layout": ["diagonal-stripe"], "symbols": ["sun"]},
    "nauru": {"colors": ["blue", "yellow", "white"], "layout": ["horizontal-stripe"], "symbols": ["star"]},
    "nepal": {"colors": ["red", "blue", "white"], "layout": ["non-rectangular", "double-pennant"], "symbols": ["sun", "moon"]},
    "netherlands": {"colors": ["red", "white", "blue"], "layout": ["horizontal-tricolor"], "symbols": []},
    "new-zealand": {"colors": ["blue", "white", "red"], "layout": ["canton"], "symbols": ["stars", "union-jack"]},
    "nicaragua": {"colors": ["blue", "white"], "layout": ["horizontal-triband", "centered-emblem"], "symbols": ["coat-of-arms", "triangle"]},
    "niger": {"colors": ["orange", "white", "green"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["disc", "sun"]},
    "nigeria": {"colors": ["green", "white"], "layout": ["vertical-triband"], "symbols": []},
    "niue": {"colors": ["yellow", "blue", "red", "white"], "layout": ["canton"], "symbols": ["stars", "union-jack"]},
    "north-korea": {"colors": ["blue", "white", "red"], "layout": ["horizontal-stripes"], "symbols": ["star", "disc"]},
    "north-macedonia": {"colors": ["red", "yellow"], "layout": ["sun-rays", "centered-emblem"], "symbols": ["sun"]},
    "norway": {"colors": ["red", "white", "blue"], "layout": ["nordic-cross"], "symbols": ["cross"]},
    "oman": {"colors": ["white", "red", "green"], "layout": ["vertical-hoist", "horizontal-tricolor"], "symbols": ["emblem", "weapon"]},
    "pakistan": {"colors": ["green", "white"], "layout": ["vertical-hoist", "solid-field"], "symbols": ["crescent", "star"]},
    "palau": {"colors": ["blue", "yellow"], "layout": ["solid-field", "centered-emblem"], "symbols": ["disc", "moon"]},
    "palestine": {"colors": ["black", "white", "green", "red"], "layout": ["horizontal-tricolor", "hoist-triangle"], "symbols": []},
    "panama": {"colors": ["white", "red", "blue"], "layout": ["quartered"], "symbols": ["stars"]},
    "papua-new-guinea": {"colors": ["red", "black", "yellow", "white"], "layout": ["diagonal-bicolor"], "symbols": ["stars", "bird"]},
    "paraguay": {"colors": ["red", "white", "blue"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["coat-of-arms"]},
    "peru": {"colors": ["red", "white"], "layout": ["vertical-triband"], "symbols": []},
    "philippines": {"colors": ["blue", "red", "white", "yellow"], "layout": ["horizontal-bicolor", "hoist-triangle"], "symbols": ["sun", "stars"]},
    "poland": {"colors": ["white", "red"], "layout": ["horizontal-bicolor"], "symbols": []},
    "portugal": {"colors": ["green", "red", "yellow", "white", "blue"], "layout": ["vertical-bicolor", "centered-emblem"], "symbols": ["coat-of-arms", "shield"]},
    "qatar": {"colors": ["maroon", "white"], "layout": ["vertical-bicolor", "serrated"], "symbols": []},
    "republic-of-abkhazia": {"colors": ["green", "white", "red"], "layout": ["horizontal-stripes", "canton"], "symbols": ["hand", "stars"]},
    "republic-of-the-congo": {"colors": ["green", "yellow", "red"], "layout": ["diagonal-tricolor"], "symbols": []},
    "romania": {"colors": ["blue", "yellow", "red"], "layout": ["vertical-tricolor"], "symbols": []},
    "russia": {"colors": ["white", "blue", "red"], "layout": ["horizontal-tricolor"], "symbols": []},
    "rwanda": {"colors": ["blue", "yellow", "green"], "layout": ["horizontal-stripes"], "symbols": ["sun"]},
    "sahrawi-arab-democratic-republic": {"colors": ["black", "white", "green", "red"], "layout": ["horizontal-tricolor", "hoist-triangle"], "symbols": ["crescent", "star"]},
    "saint-kitts-and-nevis": {"colors": ["green", "yellow", "black", "white", "red"], "layout": ["diagonal-stripe"], "symbols": ["stars"]},
    "saint-lucia": {"colors": ["blue", "yellow", "black", "white"], "layout": ["solid-field", "centered-emblem"], "symbols": ["triangle"]},
    "saint-vincent-and-the-grenadines": {"colors": ["blue", "yellow", "green"], "layout": ["vertical-tricolor", "centered-emblem"], "symbols": ["diamonds"]},
    "samoa": {"colors": ["red", "blue", "white"], "layout": ["canton"], "symbols": ["stars"]},
    "san-marino": {"colors": ["white", "blue", "yellow", "green", "red"], "layout": ["horizontal-bicolor", "centered-emblem"], "symbols": ["coat-of-arms"]},
    "sao-tome-and-principe": {"colors": ["green", "yellow", "red", "black"], "layout": ["horizontal-triband", "hoist-triangle"], "symbols": ["stars"]},
    "saudi-arabia": {"colors": ["green", "white"], "layout": ["solid-field", "centered-text"], "symbols": ["script", "sword"]},
    "scotland": {"colors": ["blue", "white"], "layout": ["diagonal-cross"], "symbols": ["saltire"]},
    "senegal": {"colors": ["green", "yellow", "red"], "layout": ["vertical-tricolor", "centered-emblem"], "symbols": ["star"]},
    "serbia": {"colors": ["red", "blue", "white", "yellow"], "layout": ["horizontal-tricolor", "emblem-left"], "symbols": ["coat-of-arms", "eagle"]},
    "seychelles": {"colors": ["blue", "yellow", "red", "white", "green"], "layout": ["radiating-bands"], "symbols": []},
    "sierra-leone": {"colors": ["green", "white", "blue"], "layout": ["horizontal-tricolor"], "symbols": []},
    "singapore": {"colors": ["red", "white"], "layout": ["horizontal-bicolor", "canton"], "symbols": ["crescent", "stars"]},
    "slovakia": {"colors": ["white", "blue", "red"], "layout": ["horizontal-tricolor", "emblem-left"], "symbols": ["coat-of-arms", "cross"]},
    "slovenia": {"colors": ["white", "blue", "red"], "layout": ["horizontal-tricolor", "emblem-left"], "symbols": ["coat-of-arms", "stars"]},
    "solomon-islands": {"colors": ["blue", "yellow", "green", "white"], "layout": ["diagonal-stripe"], "symbols": ["stars"]},
    "somalia": {"colors": ["blue", "white"], "layout": ["solid-field", "centered-emblem"], "symbols": ["star"]},
    "somaliland": {"colors": ["green", "white", "red", "black"], "layout": ["horizontal-tricolor", "centered-emblem", "centered-text"], "symbols": ["star", "script"]},
    "south-africa": {"colors": ["green", "yellow", "black", "white", "red", "blue"], "layout": ["y-shape", "horizontal-bands"], "symbols": []},
    "south-korea": {"colors": ["white", "red", "blue", "black"], "layout": ["solid-field", "centered-emblem"], "symbols": ["taeguk", "trigrams"]},
    "south-ossetia": {"colors": ["white", "red", "yellow"], "layout": ["horizontal-tricolor"], "symbols": []},
    "south-sudan": {"colors": ["black", "red", "green", "white", "blue", "yellow"], "layout": ["horizontal-stripes", "hoist-triangle"], "symbols": ["star"]},
    "spain": {"colors": ["red", "yellow"], "layout": ["horizontal-triband", "emblem-left"], "symbols": ["coat-of-arms"]},
    "sri-lanka": {"colors": ["red", "yellow", "green", "orange"], "layout": ["border", "vertical-stripes", "centered-emblem"], "symbols": ["lion", "sword", "leaves"]},
    "sudan": {"colors": ["red", "white", "black", "green"], "layout": ["horizontal-tricolor", "hoist-triangle"], "symbols": []},
    "suriname": {"colors": ["green", "white", "red", "yellow"], "layout": ["horizontal-stripes", "centered-emblem"], "symbols": ["star"]},
    "sweden": {"colors": ["blue", "yellow"], "layout": ["nordic-cross"], "symbols": ["cross"]},
    "switzerland": {"colors": ["red", "white"], "layout": ["solid-field", "centered-cross"], "symbols": ["cross"]},
    "syria": {"colors": ["red", "white", "black", "green"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["stars"]},
    "taiwan": {"colors": ["red", "blue", "white"], "layout": ["solid-field", "canton"], "symbols": ["sun"]},
    "tajikistan": {"colors": ["red", "white", "green", "yellow"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["crown", "stars"]},
    "tanzania": {"colors": ["green", "yellow", "black", "blue"], "layout": ["diagonal-stripe"], "symbols": []},
    "thailand": {"colors": ["red", "white", "blue"], "layout": ["horizontal-stripes"], "symbols": []},
    "togo": {"colors": ["green", "yellow", "red", "white"], "layout": ["horizontal-stripes", "canton"], "symbols": ["star"]},
    "tonga": {"colors": ["red", "white"], "layout": ["solid-field", "canton"], "symbols": ["cross"]},
    "transnistria": {"colors": ["red", "green", "yellow"], "layout": ["horizontal-triband", "canton"], "symbols": ["hammer-and-sickle", "star"]},
    "trinidad-and-tobago": {"colors": ["red", "black", "white"], "layout": ["diagonal-stripe"], "symbols": []},
    "tunisia": {"colors": ["red", "white"], "layout": ["solid-field", "centered-emblem"], "symbols": ["crescent", "star", "disc"]},
    "turkey": {"colors": ["red", "white"], "layout": ["solid-field"], "symbols": ["crescent", "star"]},
    "turkish-republic-of-northern-cyprus": {"colors": ["white", "red"], "layout": ["horizontal-stripes", "centered-emblem"], "symbols": ["crescent", "star"]},
    "turkmenistan": {"colors": ["green", "white", "red", "yellow"], "layout": ["solid-field", "hoist-pattern"], "symbols": ["crescent", "stars", "ornament"]},
    "tuvalu": {"colors": ["blue", "white", "red", "yellow"], "layout": ["canton"], "symbols": ["stars", "union-jack"]},
    "uganda": {"colors": ["black", "yellow", "red", "white"], "layout": ["horizontal-stripes", "centered-emblem"], "symbols": ["bird", "disc"]},
    "ukraine": {"colors": ["blue", "yellow"], "layout": ["horizontal-bicolor"], "symbols": []},
    "united-arab-emirates": {"colors": ["green", "white", "black", "red"], "layout": ["vertical-hoist", "horizontal-tricolor"], "symbols": []},
    "united-kingdom": {"colors": ["red", "white", "blue"], "layout": ["diagonal-cross", "quartered"], "symbols": ["cross", "saltire"]},
    "united-states": {"colors": ["red", "white", "blue"], "layout": ["stripes", "canton"], "symbols": ["stars"]},
    "uruguay": {"colors": ["white", "blue", "yellow"], "layout": ["stripes", "canton"], "symbols": ["sun"]},
    "uzbekistan": {"colors": ["blue", "white", "green", "red"], "layout": ["horizontal-stripes"], "symbols": ["crescent", "stars"]},
    "vanuatu": {"colors": ["red", "green", "black", "yellow"], "layout": ["y-shape", "horizontal-bands"], "symbols": ["tusk", "leaves"]},
    "vatican-city": {"colors": ["yellow", "white", "red"], "layout": ["vertical-bicolor", "centered-emblem"], "symbols": ["keys", "tiara"]},
    "venezuela": {"colors": ["yellow", "blue", "red", "white"], "layout": ["horizontal-tricolor", "centered-emblem"], "symbols": ["stars"]},
    "vietnam": {"colors": ["red", "yellow"], "layout": ["solid-field", "centered-emblem"], "symbols": ["star"]},
    "wales": {"colors": ["red", "white", "green"], "layout": ["horizontal-bicolor", "centered-emblem"], "symbols": ["dragon"]},
    "yemen": {"colors": ["red", "white", "black"], "layout": ["horizontal-tricolor"], "symbols": []},
    "zambia": {"colors": ["green", "red", "black", "orange"], "layout": ["solid-field", "fly-stripes"], "symbols": ["eagle"]},
    "zimbabwe": {"colors": ["green", "yellow", "red", "black", "white"], "layout": ["horizontal-stripes", "hoist-triangle"], "symbols": ["star", "bird"]},
}


def main():
    flags = json.loads(FLAGS_FILE.read_text(encoding="utf-8"))

    missing = []
    for flag in flags:
        tags = SPECIFIC.get(flag["id"])
        if not tags:
            missing.append(flag["id"])
            continue

        flag["colors"] = tags["colors"]
        flag["layout"] = tags["layout"]
        flag["symbols"] = tags["symbols"]

    FLAGS_FILE.write_text(json.dumps(flags, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"Updated {len(flags) - len(missing)} flags in {FLAGS_FILE}")
    if missing:
        print("Missing tags for:")
        for item in missing:
            print(" -", item)


if __name__ == "__main__":
    main()
